### ISSUE TITLE
Icoboard: "Checking 33.33 ns (30.00 MHz) clock constraint: FAILED."

### ISSUE THREAD

**Issue by piso77** [splinedrive/kianRiscV#1]
On a recent yosys+nextpnr-ice40 checkout, while trying to build for Icoboard:

...
Info: Program finished normally.
#nextpnr-ice40 -r --pre-pack clocks.py --hx8k --package ct256  --json kianv_soc_icoboard.json --asc kianv_soc_icoboard.asc --opt-timing --pcf icosoc.pcf
#nextpnr-ice40 -r --freq 30 --hx8k --package ct256  --json kianv_soc_icoboard.json --asc kianv_soc_icoboard.asc --pcf icosoc.pcf
icetime -c 30 -d hx8k -mtr kianv_soc_icoboard.rpt kianv_soc_icoboard.asc
// Reading input .asc file..
// Reading 8k chipdb file..
// Creating timing netlist..
// Timing estimate: 37.31 ns (26.80 MHz)
// Checking 33.33 ns (30.00 MHz) clock constraint: FAILED.
make: *** [Makefile.icoboard:30: kianv_soc_icoboard.rpt] Error 1

**Comment by splinedrive** [comment]
You should disable the constraint.i don't know which nextpnr and yosys do you have.  I have the latest

**Comment by piso77** [comment]
I lowered the frequency to 25Mhz, and it builds fine (though i'm struggling building firmware now):

diff --git a/simple/socs/Makefile.icoboard b/simple/socs/Makefile.icoboard
index 684f60e..ba33ef6 100644
--- a/simple/socs/Makefile.icoboard
+++ b/simple/socs/Makefile.icoboard
@@ -11,7 +11,7 @@ FILES := kianv_soc_icoboard.v \
                                 oled_sdd1331.v
                                 #my_vga_clk_generator.v \
 
-FREQ := 30
+FREQ := 25
 all: $(PROJ).rpt $(PROJ).bin
 
 %.blif: %.v
